### PR TITLE
Closes#63

### PR DESCRIPTION
**Pull request by hanenWahabi**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
We should use `localStorage.removeItem(key);` instead of setting the key to null if I recall correctly

**Review by etorres07 — CHANGES_REQUESTED** [review]
@hanenWahabi it works well from `GiveAnswer.js` in the sense that it redirects to `Home.js` and displays the questions that match the query. Great job! 👍 

I have 2 feedback points, in case they can be implemented before merging:
1. The functionality doesn't work from `NewQuestion.js` but only from `GiveAnswer.js`
2. Once the user is redirected from `GiveAnswer.js` to `Home.js` after searching, there is no way for the user to see all the questions unless he/she manually refreshes

Let me know what you think of these, if you think they seem doable or you have any other comment.

**Comment by hanenWahabi** [comment]
thank you!
Yes I didn't add code to NewQuestion.js but it's the same code in GiveAnswer.js and for the second bug we should add Home item to the side list like stackoverflow to refresh.

**Comment by etorres07** [comment]
Ok, @hanenWahabi!

I have updated your PR to include the search functionality in `NewQuestion.js` as it was implemented in `GiveAnswer.js`. We can continue the conversation on the side list item in issue #95.

Thank you!

**Pull request merged**
